# Generated by Django 4.2.1 on 2023-05-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onirix', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.CharField(choices=[('$38', '$38'), ('$50', '$50')], default='', max_length=3)),
            ],
        ),
    ]
